title: Bitnation Pangea
description: Your Blockchain Jurisdiction
author: Bitnation

url: https://camilolunacom.github.io

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-polyglot
  
permalink: /:title/

theme: []

sass:
  # style: compressed
  sourcemap: true

exclude:
  - .gitignore
  - CNAME
  - readme.md
  - Gemfile
  - Gemfile.lock
  - docs

google_analytics_id: UA-106469149-1

languages: ["en", "es"]
default_lang: "en"
exclude_from_localization: ["css", "img", "js", "robots.txt", "sitemap.xml", "favicon.ico"]
parallel_localization: true
rtl_languages: ["ar"]

language_names:
  ar: <span dir="rtl">العَرَبِيَّة</span>
  ca: Catalan
  de: Deutsch
  en: English
  es: Español
  fil: Filipino
  fr: Français
  it: Italiano
  ja: 日本語
  ko: 한국어
  pt: Português
  ru: Русский
  vi: Tiếng Việt
  zh: 國語

video:
  de: 7BN7AP7qV3k
  en: CL4eM9JyL08
  es: kVe55fETChg
  fr: RSnkabu83Zg
  it: lZHjn7VAjJs
  ja: u3GIqrcW4DM
  ko: FhqZmEGCWLw
  pt: QNT94v8ZUSc
  ru: Q7SLulIaKaY
  vi: b1ntuS7M1is
  zh: g_yw1rbnZi0