title: Bitnation Pangea
description: Your Blockchain Jurisdiction
author: Bitnation
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-polyglot
permalink: /news/:year-:month/:title/

sass:
  style: compressed

exclude:
  - .gitignore
  - CNAME
  - readme.md

google_analytics_id: UA-106469149-1

languages: ["en", "sv", "de", "fr"]
default_lang: "en"
exclude_from_localization: ["js", "img", "css"]
parallel_localization: true