title: Bitnation Pangea
description: Your Blockchain Jurisdiction
author: Bitnation

url: https://tse.bitnation.co

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-polyglot
  
permalink: /:title/

destination: docs
theme: []

sass:
  # style: compressed
  sourcemap: true

exclude:
  - .gitignore
  - CNAME
  - readme.md
  - Gemfile
  - Gemfile.lock
  - docs

google_analytics_id: UA-106469149-1

languages: ["ar", "ca", "de", "en", "es", "fil", "fr", "it", "ja", "pt", "ru", "vi", "zh"]
default_lang: "en"
exclude_from_localization: ["css", "img", "js", "robots.txt", "sitemap.xml", "favicon.ico"]
parallel_localization: true

language_names:
  ar: <span dir="rtl">العَرَبِيَّة</span>
  ca: Catalan
  de: Deutsch
  en: English
  es: Español
  fil: Filipino
  fr: Français
  it: Italiano
  ja: 日本語
  pt: Português
  ru: Русский
  vi: Tiếng Việt
  zh: 國語
